### ISSUE TITLE
france 1 - 5 not working anymore

### ISSUE THREAD

**Issue by newtestpage** [ipstreet312/freeiptv#11]
Hi 

france 1,2,3,4,5

are not working anymore . Could you fix it ?

**Comment by ipstreet312** [comment]
Hello,
Thank you for your message.
You should and you can create your own link dedicated to france tv.
Please find here the procedure for : https://receptioniptv.blogspot.com/2023/04/how-to-build-link-including-php-to-get.html
Please find here sources files to use : https://github.com/ipstreet312/freeiptv/tree/master/feed
Best regards

**Comment by newtestpage** [comment]
Thanks for your response . I did it and change the permission to 755 . but it is not working yet .

**Comment by ipstreet312** [comment]
> Thanks for your response . I did it and change the permission to 755 . but it is not working yet .

Hello, it is working, checked just from my side.
