### ISSUE TITLE
Add Equidia

### ISSUE THREAD

**Issue by schumijo** [ipstreet312/freeiptv#12]
Hi,

Do you think it is possible to add Equidia streams ?

Strem url change on each connection but can be obtain with this method :
Open this link : 
`https://api.equidia.fr/api/public/racing/directs/live2/hls?urlOnly=true `
to obtain a php file that contain m3u8 URL.

Or maybe use the m3u8 file from here : http://callofliberty.fr/stream/EQUIDIA/master.m3u8

**Comment by ipstreet312** [comment]
Hello thank you for your interest and given infos.
Unfortunately I dont have deep php skills for a solution.
Best regards see you soon

**Comment by mikhoul** [comment]
Right  now I don't have the time but after september I will look at it to see if I can make a php script.

**Comment by ipstreet312** [comment]
ooh ! thank you a lot, bests & cheers

**Comment by schumijo** [comment]
I don't think it is necessary to do a PHP script. Just do some GET with python to obtain content of PHP file as you did with other channels. Maybe I will take a look next days

**Comment by ipstreet312** [comment]
Yes thank you a lot, just it is referring two link in cascade with intermediary, that's why i was not sure to be able to use a GET with py done like easily directly for some channels in the m3u. Thanks again & bests !

**Comment by ipstreet312** [comment]
Hi again @schumijo thank you a lot and very much for equidia, and i fixed the master presentation in m3u issue from my side. Bests

**Comment by schumijo** [comment]
Hi @ipstreet312 
You can find all Equidia streams in my repo 
https://github.com/schumijo/iptv/tree/main/parser
