### ISSUE TITLE
add channels

### ISSUE THREAD

**Issue by gio299** [ipstreet312/freeiptv#16]
hi! 
Can you add please the channels?

Star Kentrikis Elladas  | Greece|
https://www.dailymotion.com/video/xqjey2

Euronews Greece  | | |
https://www.dailymotion.com/video/x2j7kha

**Comment by ipstreet312** [comment]
Hello @gio299  ! Thank you for your message and interest. As greek channel are in few numbers only, missing like ERTs Ant1 Mega etc. it is not relevant to open a Tab for greek channel thema to add.
But for the two dailym online greek channels, you can use similary and follow the mechanical logic like codes here to create Stream link for theses channels : https://github.com/ipstreet312/freeiptv/tree/master/ressources/dmotion/py
Bests and Cheers
