### ISSUE TITLE
about the algerian channels 

### ISSUE THREAD

**Issue by hemzaberkane** [ipstreet312/freeiptv#17]
hello .
i have some problems with this three channels , thats work fine on tivimate but dont work on smartiptv on samsung tizen tv 
#EXTINF:-1 tvg-id="EchoroukTV.dz" tvg-logo="https://raw.githubusercontent.com/hemzaberkane/AlgeriaPicons/main/echorouk.png", Echorouk  الشروق 
https://echorouk-live-tv.dzsecurity.net/fullres/EchoroukTV_First/chunks.m3u8|Referer=https://echorouk.dzsecurity.net/embed/echorouk.php

#EXTINF:-1  tvg-logo="https://raw.githubusercontent.com/hemzaberkane/AlgeriaPicons/main/echorouknews.png" ,Echorouk News الشروق الإخبارية
https://echorouk-live-tv.dzsecurity.net/fullres/EchoroukNews_First/chunks.m3u8|Referer=https://echorouk.dzsecurity.net/embed/echorouk.php

#EXTINF:-1  tvg-logo="https://raw.githubusercontent.com/hemzaberkane/AlgeriaPicons/main/ennahar.png" ,Ennahar News النهار 
https://ennahar-live.dzsecurity.net/fullres/EnnaharTV_First/chunks.m3u8|Referer=https://echorouk.dzsecurity.net/embed/echorouk.php

**Comment by ipstreet312** [comment]
Merci thank you a lot , i will add them even if smartiptv restriction on referrer as it is not managed. 
One year before, all channels were ok with hta hasnaoui telecom algeria official broadcast servers.
Regards

**Comment by hemzaberkane** [comment]
bonjour .
can you help me with this channels on bledflix website 
this channels contain 3 links , each link work voice without image or the opposite 
this is an example of el bilad tv 
image https://bledflix-el-bilad.b-cdn.net/media_0.m3u8
voice https://bledflix-el-bilad.b-cdn.net/media_3.m3u8

**Comment by ipstreet312** [comment]
Bonjout @hemzaberkane , 
Merci for you message, I was off and out, sorry for the delay.
Please find issue as solved there to use on siptv where working fine, tested :
https://raw.githubusercontent.com/ipstreet312/freeiptv/master/ressources/dzflix/elbilad.m3u8
You can tell me other dz channels that I can add for the all community of all.m3u users !
Merci again ! Thanks & Regards

**Comment by hemzaberkane** [comment]
merci beaucoup .
here is the other channels 
echorouk tv 
https://bledflix-echorouk-tv.b-cdn.net/media_0.m3u8
https://bledflix-echorouk-tv.b-cdn.net/media_1.m3u8
https://bledflix-echorouk-tv.b-cdn.net/media_2.m3u8
https://bledflix-echorouk-tv.b-cdn.net/media_3.m3u8
https://bledflix-echorouk-tv.b-cdn.net/media_4.m3u8
echorouk news 
https://bledflix-echorouk-news.b-cdn.net/media_0.m3u8
https://bledflix-echorouk-news.b-cdn.net/media_1.m3u8
https://bledflix-echorouk-news.b-cdn.net/media_2.m3u8
https://bledflix-echorouk-news.b-cdn.net/media_3.m3u8
samira tv
https://bledflix-samira-tv.b-cdn.net/media_0.m3u8
https://bledflix-samira-tv.b-cdn.net/media_1.m3u8
https://bledflix-samira-tv.b-cdn.net/media_2.m3u8
https://bledflix-samira-tv.b-cdn.net/media_3.m3u8

**Comment by hemzaberkane** [comment]
what about samira tv , cause the link that you out in all.m3u8 dont worked

**Comment by ipstreet312** [comment]
> what about samira tv , cause the link that you out in all.m3u8 dont worked

That's for the signaling, i will add it within the day. Thanks again, keeping in touch

**Comment by hemzaberkane** [comment]
thanks a lot , hve nice day

**Comment by hemzaberkane** [comment]
hi 
nessma tv 
https://fflivenessma.b-cdn.net/media_0.m3u8
https://fflivenessma.b-cdn.net/media_1.m3u8
https://fflivenessma.b-cdn.net/media_2.m3u8
https://fflivenessma.b-cdn.net/media_3.m3u8

**Comment by ipstreet312** [comment]
Hiiii thanks a lott !
From DM source, link gathering is geoblocked unfortunately :
https://github.com/ipstreet312/freeiptv/tree/master/ressources/dmotion/py/nessma
Thanks again for your link, akamaized was off latestly.
Nessma updated, Regards
