### ISSUE TITLE
cnews and other stuff

### ISSUE THREAD

**Issue by campones** [ipstreet312/freeiptv#23]
this cnews  is dead
https://hls-m013.live-lv3.canalplus-cdn.net/live/disk/cnews-clair-hd/hls-ios-fhd-clair/cnews-clair-hd.m3u8

beside that I was wondering, I see you are doing a lot of python script scrapper.  why don't you make them for streamlink?
I mean, basically all the dailymotion french channel are available there already?  (on streamlink)

**Comment by ipstreet312** [comment]
Hello, thank you for your report.
I like the diversity of sources and I prefer to distribute the loads on the servers.
I added cnews via dmotion, directly without streamlink, actually having a ready-made code for,
Best regards

**Comment by campones** [comment]
Salut
je viens de voir que le bash script pour recuperer les flux de france tv ne semble plus fonctionnel. 
ou alors c'est un bug temporaire.
https://github.com/ipstreet312/freeiptv/blob/master/ressources/ftv/php/fr2.php

**Comment by ipstreet312** [comment]
> Salut je viens de voir que le bash script pour recuperer les flux de france tv ne semble plus fonctionnel. ou alors c'est un bug temporaire. https://github.com/ipstreet312/freeiptv/blob/master/ressources/ftv/php/fr2.php

apres cnews ça maintenant fait chier sale journée suis fatigué ils fatiguent bref mise à jour en cours, dispos sous peu, la haine du stream ! ^^evil^ sinon maj siptv ce jour avec referer inclu géré trop bon ^^

**Comment by campones** [comment]
ouai comme je le l imaginais, le script marche tj.  ça plantait sur le moment et ils ont changé les tracks de la playlist, on est passé de 4 track a 3 


#!/bin/bash/

source=$(curl https://hdfauth.ftven.fr/esi/TA?url=https://simulcast-p.ftven.fr/simulcast/France_3/hls_fr3/index.m3u8)
echo "$source"

/usr/local/bin/ffmpeg -user_agent "AppleCoreMedia/1.0.0.16H62 (iPhone; U; CPU OS 12_5_5 like Mac OS X; fr_be)" -re -i "$source" -map p:3:0 -map p:3:2 -c copy -f flv  coucou.network.hello

**Comment by ipstreet312** [comment]
ok @campones merci . sur le coup j'ai crée 3 (backup) frtv miammiam :))

**Comment by ipstreet312** [comment]
@campones bonjour j'espere vous allez bien. pour info voici la nouvelle structure du lien cnews by cplus-cdn fonctionnelle actuellement encore : https://hls-m013.p-cdnlive-edge020311-dual.scy.canalplus-cdn.net/__token__id%3D1a569a48e47690c700c0f71662c87679~hmac%3D6d2114baa9bb694f530073a9f707530612577a89d4d0a36aaa72374fa9e12049/live/disk/cnews-clair-hd/hls-v3-hd-clair/cnews-clair-hd.m3u8
