### ISSUE TITLE
Searching links for channels from malta 

### ISSUE THREAD

**Issue by hemzaberkane** [ipstreet312/freeiptv#25]
tv malta 
https://tvmi.mt/live/2
tv malta news 
https://tvmi.mt/live/3
tv malta sports 
https://tvmi.mt/live/4
one tv 
https://2-fss-1.streamhoster.com/pl_148/201830-1293592-1/chunklist.m3u8
net tv 
https://netondemand.mt/?autoPlay=1

**Comment by ipstreet312** [comment]
Hello I started to look at, added to my todo tasks, I will update you here in few days. Regards

**Comment by ipstreet312** [comment]
Hello again, i triyed but it seems ipadr based blocked, anyway i share you the work tentative : 
https://gist.github.com/ipstreet312/1bc97b4ed6ac7374457f5c88549c836a
