### ISSUE TITLE
problem all.m3u

### ISSUE THREAD

**Issue by Jeanot71** [ipstreet312/freeiptv#26]
hello sorry for my language i am french.
in the files all.m3u
the channel with a adresse https://raw.githubusercontent.com/ipstreet312/freeiptv/master/ressources/ftv/py  dont work all 

exemple don't work

#EXTINF:-1 tvg-logo="https://i.ibb.co/GxWtcTm/fr2bl.png",FRANCE 2
https://raw.githubusercontent.com/ipstreet312/freeiptv/master/ressources/ftv/py/fr2.m3u8
#EXTINF:-1 tvg-logo="https://i.ibb.co/y8PjbJ4/fr3bl.png",FRANCE 3
https://raw.githubusercontent.com/ipstreet312/freeiptv/master/ressources/ftv/py/fr3.m3u8
#EXTINF:-1 tvg-logo="https://i.ibb.co/VgcrtZ5/fr4blok.png",FRANCE 4
https://raw.githubusercontent.com/ipstreet312/freeiptv/master/ressources/ftv/py/fr4.m3u8
#EXTINF:-1 tvg-logo="https://i.ibb.co/N9d4yXt/fr5bl.png",FRANCE 5
https://raw.githubusercontent.com/ipstreet312/freeiptv/master/ressources/ftv/py/fr5.m3u8
#EXTINF:-1 tvg-logo="https://i.ibb.co/9rmSGqP/frsr.png",FRANCE SÉRIES
https://raw.githubusercontent.com/ipstreet312/freeiptv/master/ressources/ftv/py/frsr.m3u8

have you a new adress ?

thank you

**Comment by ipstreet312** [comment]
Hello thanks for the report, some alternances seen and noticed sometimes from francetv feeds but it depends also of the used internet providers which could be strange, currently it is working, good to you
