### ISSUE TITLE
RTP Memoria Portugal isnt working.

### ISSUE THREAD

**Issue by spotanjo3** [ipstreet312/freeiptv#3]
https://streaming-live.rtp.pt/liverepeater/smil:rtpmem.smil/playlist.m3u8

**Comment by ipstreet312** [comment]
Hello, it's working fine, checked, and without need of a user-agent specific usage requesting. But stream is not available 24/24 continuously, regards.

**Comment by spotanjo3** [comment]
Thank you. Keep up the good work. Cant wait for more Portugal channels. Hope to see discovery and National Geographic and maybe HBO? Good work!

**Comment by thomraider12** [comment]
> Thank you. Keep up the good work. Cant wait for more Portugal channels. Hope to see discovery and National Geographic and maybe HBO? Good work!

HBO doesn't exist in Portugal 😅
National Geographic and Discovery Channel are more of private channels, so you probably won't see them here too.

**Comment by ipstreet312** [comment]
Do you or s/o have NOW TV NEWS PORTUGAL ?

**Comment by thomraider12** [comment]
> Do you or s/o have NOW TV NEWS PORTUGAL ?

No, it is a private channel like CMTV (by the way, News Now is from the company of CMTV). I would like to have it too, but it's private 😅

**Comment by spotanjo3** [comment]
> > Thank you. Keep up the good work. Cant wait for more Portugal channels. Hope to see discovery and National Geographic and maybe HBO? Good work!
> 
> HBO doesn't exist in Portugal 😅 National Geographic and Discovery Channel are more of private channels, so you probably won't see them here too.

Yeah, I realised that it was for Brazil. Not Portugal. Oh well. Thanks.
