### ISSUE TITLE
Isuues For Arabic channels

### ISSUE THREAD

**Issue by hemzaberkane** [ipstreet312/freeiptv#31]
Roya News From Jordan 
https://roya.tv/live-stream/21

**Comment by ipstreet312** [comment]
Thank you but royanews link is tokenized i checked

**Comment by ipstreet312** [comment]
Hi again @hemzaberkane ,

I found mechanism : https://ticket.roya.tv/api/v3/fastchannel/21  {also value : 19;->->-;22 etc.}
If mechanism were difficult, we could open a tv channel plugin request on streamlink/streamlink github project.

I written python code and here its m3u8 output :
https://github.com/ipstreet312/freeiptv/blob/master/ressources/extr/py/royanews.m3u8
But link is not working and based on ip-adress protection.

Here Youtube based fetch working link :
https://raw.githubusercontent.com/MassinDV/Youtube-arabic-channels/main/live/ch39.m3u8
Added on my m3u playlist btw, thanks
