### ISSUE TITLE
about     algerians channels

### ISSUE THREAD

**Issue by hemzaberkane** [ipstreet312/freeiptv#32]
the alagerians channels like echorouk and aennahar does not work on referrer any more

**Comment by ipstreet312** [comment]
Hi just checked now working well.
But Ennahar was always ko fyi.

**Comment by hemzaberkane** [comment]
but for me dont work on tivimate

**Comment by hemzaberkane** [comment]
BONJOUR .
LES CHAINES ALGERIENS NE MARCHE PLUS (ECGOROUK /ENNAHAR/ELHAYAT/ ECOROUKEWS)
voici les sites weboffcielle des chaines concernè : 
https://www.ennaharonline.com/live/
https://www.echoroukonline.com/live
https://elhayat.dz/%d8%a7%d9%84%d8%a8%d8%ab-%d8%a7%d9%84%d8%ad%d9%8a/

**Comment by ipstreet312** [comment]
@hemzaberkane  update  :
while opening request on Streamlink if any, you should precise :
https://hls-players.dzsecurity.net/live/player/elhayattv is OK with referer = https://elhayat.dz/
