### ISSUE TITLE
M6 + M6 international stoped working.

### ISSUE THREAD

**Issue by mikhoul** [ipstreet312/freeiptv#35]
https://shls-m6-int-prod-dub.shahid.net is dead, maybe it have been replaced with another domain name ???

Regards ! :octocat:

**Comment by ipstreet312** [comment]
Hi thanks for your reporting and notification, i don't know if there is a new variant link for it at the moment. Thanks & Regards ;) Love to stream

**Comment by campones** [comment]
we need an update on this, if any
