### ISSUE TITLE
Broken m3u file.

### ISSUE THREAD

**Issue by knxwille** [ipstreet312/freeiptv#36]
all.m3u file is not well formatted. That causing parse errors on some iptvplayers. Especially group lists are looks empty or only one channel in it.
Please use some kind of "playlist optimiser" before release.

Thank you for your great effort.

knx.

**Comment by ipstreet312** [comment]
Hi, thanks for your interest. Here the auto generated suitable format for your need : 
https://github.com/ipstreet312/freeiptv/blob/master/ressources/allgr.m3u
Info here : https://receptioniptv.blogspot.com/2024/01/short-url-m3u-and-systematic-group.html 
Regards
