### ISSUE TITLE
SIC Notícias (Portugal)

### ISSUE THREAD

**Issue by thomraider12** [ipstreet312/freeiptv#38]
Suddenly SIC Notícias has lost signal and is not working at least for me. Hope you can resolve it. And don't use the link https://sicnot.live.impresa.pt/sicnot.m3u8 cause it gives me a 403 error and I'm from Portugal, so I shoudnt be geoblocked.

Thank you.

**Comment by ipstreet312** [comment]
it is OK checked, thanks regards
