### ISSUE TITLE
Wrong channel.

### ISSUE THREAD

**Issue by spotanjo3** [ipstreet312/freeiptv#4]
#EXTINF:0 tvg-logo="https://i.ibb.co/6r1xHn6/sic.png",SIC INT
https://d1zx6l1dn8vaj5.cloudfront.net/out/v1/b89cc37caa6d418eb423cf092a2ef970/index.m3u8

Its working but it is not SIC Internacional. It is just "SIC". Do you have SIC Internacional ? The logo on the top left in the TV should show:

SIC
INTERNACIONAL logo.

**Comment by ipstreet312** [comment]
update done
