### ISSUE TITLE
Greek Channels

### ISSUE THREAD

**Issue by worldmediaman** [ipstreet312/freeiptv#40]
#EXTINF:-1 group-title="🇬🇷 GREECE" tvg-id="AlphaTV.gr" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/3/3f/Alpha-TV-Logo.png",Alpha TV  
http://alphatvlive.siliconweb.com/1/Y2Rsd1lUcUVoajcv/UVdCN25h/hls/live/playlist.m3u8
#EXTINF:-1 tvg-id="ANT1Greece(src01).gr" tvg-logo="https://upload.wikimedia.org/wikipedia/el/thumb/3/3a/ANT1_Greek_channel_logo.svg/1024px-ANT1_Greek_channel_logo.svg.png" ,ANT1
http://l2.cloudskep.com/ant1cm2/abr/playlist.m3u8
#EXTINF:-1 tvg-id="ANT1Greece(src01).gr" tvg-logo="https://upload.wikimedia.org/wikipedia/el/thumb/3/3a/ANT1_Greek_channel_logo.svg/1024px-ANT1_Greek_channel_logo.svg.png" ,ANT1 HD
https://d1nfykbwa3n98t.cloudfront.net/out/v1/6e5667da5a6843899a337dea72adb61b/antenna_1.m3u8
#EXTINF:-1 tvg-id="ATTICA TV" tvg-logo="https://i.ibb.co/HgLW7sN/attica.jpg" , ATTICA
http://atticatv.siliconweb.com/atticatv/atticaliveabr/playlist.m3u8
#EXTINF:-1,ERT World
https://ertflix.s.llnwi.net/ertlive/ertworld/default/index.mpd
#EXTINF:-1 tvg-id="Skai(src01).gr" tvg-name="SKAI" tvg-logo="https://www.thessalonikiguide.gr/wp-content/uploads/2020/04/skai-logo.jpg" , SKAI
https://skai-live.siliconweb.com/media/cambria4/index.m3u8
#EXTINF:-1 tvg-id="star.gr" tvg-logo="https://i.ibb.co/7Gj7KTj/star.jpg" , star HD
#https://livestar.siliconweb.com/media/star1/star1mediumhd.m3u8
#EXTINF:-1 tvg-id="MakedoniaTV.gr" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/7/7a/Makedonia_TV_2023.svg",Makedonia TV 
https://dlm34ll53zqql.cloudfront.net/out/v1/d4177931deff4c7ba994b8126d153d9f/maktv_4.m3u8
#EXTINF:-1 tvg-id="Mega" tvg-logo="https://i.ibb.co/f2rCKjh/mega.jpg" , MEGA
#https://c98db5952cb54b358365984178fb898a.msvdn.net/live/S86713049/gonOwuUacAxM/playlist.m3u8
#EXTINF:-1 tvg-id="OPEN BEYOND" tvg-logo="https://img.onesignal.com/t/aa4f01d5-1349-424d-9c50-6ccfcf20dd0d.png" , OPEN BEYOND
https://liveopencloud.siliconweb.com/1/ZlRza2R6L2tFRnFJ/eWVLSlQx/hls/live/playlist.m3u8
#EXTINF:-1 tvg-id="SigmaTV.cy" tvg-logo="http://www.sigmatv.com/application/themes/default/img/redesign/sigma-logo-final.png" ,Sigma TV
https://sl2.sigmatv.com/hls/live.m3u8
#EXTINF:-1 tvg-id="ACTION24" tvg-logo="https://i.ibb.co/QXfLP4j/action24.png" ,Action 24  
https://actionlive.siliconweb.com/actionabr/actiontv/playlist.m3u8
#EXTINF:-1 tvg-id="ERTWorld.gr" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/b/bc/ChannelLogo-ERTWORLD1.png",ERT World
#https://cbd537474fbad4634b64787657ff6456.msvdn.net/ertworld/ert_world_main/mainabr/playlist_dvr.m3u8
#EXTINF:-1 tvg-id="TVM" tvg-logo="https://i.ibb.co/7gQWfqM/aeolos.jpg"  , AEOLOS  
https://cdn.istoikona.com/aeolostv/live/playlist.m3u8
#EXTINF:-1 tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Logo_RIK_Sat_2017.svg/640px-Logo_RIK_Sat_2017.svg.png" , RIK Sat
http://l3.cloudskep.com/cybcsat/abr/playlist.m3u8
#EXTINF:-1  tvg-logo="https://goo.gl/ofVjvQ" ,NETV TORONTO
https://eu1.vectromdigital.com:1936/netvtoronto/netvtoronto/playlist.m3u8
#EXTINF:-1 tvg-logo="https://goo.gl/ofVjvQ" ,NETV EUROPE
https://eu1.vectromdigital.com:1936/netveurope/netveurope/playlist.m3u8
#EXTINF:-1 tvg-id="NetmaxTV.gr" tvg-logo="http://netmaxtv.com/wp-content/uploads/2020/07/forweb.png" , Netmax TV 
http://live.netmaxtv.com:8080/live/live/playlist.m3u8
#EXTINF:-1 tvg-id="GroovyTV.gr"  tvg-logo="https://reloadplay.com/wp-content/uploads/2017/04/Groovy-3-150x48.png" ,Groovy TV
http://web.onair-radio.eu:1935/groovytv/groovytv/playlist.m3u8
#EXTINF:-1 tvg-id="NeaTV.gr" tvg-id="NEA TV CRETE" tvg-logo="https://goo.gl/WSfOWs" ,Nea TV 
https://live.neatv.gr:8888/hls/neatv_high/index.m3u8
#EXTINF:-1 tvg-logo="https://i.ibb.co/k9dGbcN/baraza.jpg" ,Baraza Relaxing TV
https://rtmp.streams.ovh:1936/barazarelax/barazarelax/playlist.m3u8
#EXTINF:-1 tvg-logo="http://i.imgur.com/QZQhg6C.png" , Magic TV
https://itv.streams.ovh/magictv/magictv/playlist.m3u8
#EXTINF:-1 tvg-logo="https://4.bp.blogspot.com/-BjVgNNmExgo/WhMYN1dmDHI/AAAAAAAAXTY/TmPb086-0acq-FzrTVn7eNqLDF9BU7VvwCLcBGAs/s1600/xalastra%2Btv.jpg" , Xalastra TV
https://live.cast-control.eu:443/xalastratv/xalastratv/playlist.m3u8
#EXTINF:-1 tvg-logo="https://i.imgur.com/1Zl1OJ5.png" , NRG TV
http://tv.nrg91.gr:1935/onweb/live/master.m3u8
#EXTINF:-1,EXPLORE
http://web.onair-radio.eu:1935/explorecy/explorecy/playlist.m3u8
#EXTINF:-1,BOYAH TV
http://streamer-cache.grnet.gr/parliament/hls/webtv.m3u8
#EXTINF:-1,TOP CHANNEL
http://eu1.vectromdigital.com:1935/topchannel/topchannel/playlist.m3u8
#EXTINF:-1,ράκη Νετ TV
https://cdn.onestreaming.com/thrakinettv/thrakinettv/playlist.m3u8
#EXTINF:-1,Tele ΚΡΗΤΗ
https://neon.streams.gr:8081/telekriti/index.m3u8
#EXTINF:-1,ERT SPORTS
https://ertflix.s.llnwi.net/ertlive/ertsports1/default/index.mpd
#EXTINF:-1,ERT 1 Geoblocking
https://ertflix.s.llnwi.net/ertlive/ert1/encdef/index.mpd
#EXTINF:-1,ERT 2 Geoblocking
https://ertflix.s.llnwi.net/ertlive/ert2/default/index.mpd
#EXTINF:-1,ERT 3 Geoblocking
https://ertflix.s.llnwi.net/ertlive/ert3/clrdef24620/index.mpd
#EXTINF:-1,ERT NEWS Geoblocking
https://ertflix.s.llnwi.net/ertlive/ertnews/default/index.mpd
#EXTINF:-1,START TV 
https://live.cast-control.eu/StartMedia/StartMedia/playlist.m3u8
#EXTINF:-1,pella TV
https://video.streams.ovh:1936/pellatv/pellatv/master.m3u8
#EXTINF:-1,KONTRA TV 
http://kontralive.siliconweb.com/live/kontratv/playlist.m3u8
#EXTINF:-1,High TV 
http://live.streams.ovh:1935/hightv/hightv/playlist.m3u8
#EXTINF:-1,Hellenic TV 
https://l5.cloudskep.com/hellenictv/htv/playlist.m3u8
#EXTINF:-1,Greek TV London 
https://vdo3.alphaserver.gr:3466/live/greektvlondonlive.m3u8
#EXTINF:-1,GRD Channel
https://live.cast-control.eu:443/organismos/organismos/playlist.m3u8
#EXTINF:-1,CRETA
http://live.streams.ovh:1935/tvcreta/tvcreta/playlist.m3u8
#EXTINF:-1,CORFU
https://itv.streams.ovh/corfuchannel/corfuchannel/playlist.m3u8
#EXTINF:-1,BLUE SKY
https://cdn1.smart-tv-data.com/bluesky/bluesky-live/playlist.m3u8

**Comment by ipstreet312** [comment]
@worldmediaman Done ! Thanks ;)
