### ISSUE TITLE
German Channels

### ISSUE THREAD

**Issue by worldmediaman** [ipstreet312/freeiptv#41]
German Channels Works without Geoblocking!

#EXTINF:-1,ARD
https://daserste-live.ard-mcdn.de/daserste/live/hls/int/master.m3u8
#EXTINF:-1,ARD
https://mcdn.daserste.de/daserste/de/master.m3u8
#EXTINF:-1  ProSieben
http://85.187.13.40:18000/ProSieben
#EXTINF:-1 , Anixe TV
https://ma.anixa.tv/clips/stream/anixehd/index.m3u8
#EXTINF:-1 , RTL
https://ma.anixa.tv/clips/stream/rtl/index.m3u8
#EXTINF:-1 , RTL SUPER
https://bozztv.com/trn09/gin-superrtl/index.m3u8
#EXTINF:-1 , dokusat 
https://muc3.iptv-playoutcenter.de/dokusat/dokusat1/playlist.m3u8
#EXTINF:-1 , Welt der wunder
https://wdw.iptv-playoutcenter.de/wdw/wdw1/playlist.m3u8
#EXTINF:-1 , noa4 Hamburg HD
https://hls1.wtnet.de/noa4hh/apple/wifi6500.m3u8
#EXTINF:-1,ARD Alpha
https://mcdn.br.de/br/fs/ard_alpha/hls/de/master.m3u8
#EXTINF:-1,ARD Tagesschau
https://tagesschau.akamaized.net/hls/live/2020115/tagesschau/tagesschau_1/master.m3u8
#EXTINF:-1,BR Nord
https://mcdn.br.de/br/fs/bfs_nord/hls/de/master.m3u8
#EXTINF:-1,HR
https://hrhls.akamaized.net/hls/live/2024525/hrhls/master.m3u8
#EXTINF:-1,SR
https://srfs.akamaized.net/hls/live/689649/srfsgeo/index.m3u8
#EXTINF:-1,WDR (weltweit)
https://mcdn.wdr.de/wdr/wdrfs/de/master.m3u8
#EXTINF:-1, More than Sports TV
https://mts1.iptv-playoutcenter.de/mts/mts-web/playlist.m3u8
#EXTINF:-1  ,Euronews Deutsch 
https://jmp2.uk/SamsungTVPlus/DEBA1000003IM.m3u8
#EXTINF:-1  , DW
https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/stream05/streamPlaylist.m3u8
#EXTINF:-1 ,Deluxe Music
https://sdn-global-live-streaming-packager-cache.3qsdn.com/13456/13456_264_live.m3u8

**Comment by ipstreet312** [comment]
thanks. done/added
