### ISSUE TITLE
Italian Channels works!

### ISSUE THREAD

**Issue by worldmediaman** [ipstreet312/freeiptv#42]
#EXTINF:-1 tvg-name="Class CNBC" tvg-logo="https://i.imgur.com/oAiSU8O.png" tvg-id="ClassCNBC.it" group-title="Italy",Class CNBC
https://859c1818ed614cc5b0047439470927b0.msvdn.net/live/S57048752/8raQqCXozN1H/playlist.m3u8
#EXTINF:-1 tvg-name="LaC News 24" tvg-logo="https://i.imgur.com/02vCECa.png" group-title="Italy",LaC News 24
https://f5842579ff984c1c98d63b8d789673eb.msvdn.net/live/S27391994/HVvPMzy/playlist.m3u8
#EXTINF:-1 tvg-chno="15" tvg-id="teleticino" tvg-name="Teleticino" tvg-logo="http://odmsto.com/uploads/tv_image/sm/teleticino.png" ,Teleticino
https://vstream-cdn.ch/hls/teleticino_720p/index.m3u8
#EXTINF:-1 tvg-id="Rai3.it",Rai 3 
https://wzstreaming.rai.it/TVlive/smil:liveStream.smil/playlist.m3u8
#EXTINF:-1 tvg-name="La7" tvg-logo="https://i.imgur.com/F90mpSa.png" tvg-id="La7.it" group-title="Italy",La7
https://d15umi5iaezxgx.cloudfront.net/LA7/CLN/HLS-B/Live.m3u8
#EXTINF:-1 tvg-name="La7d" tvg-logo="https://i.imgur.com/AOL9nMw.png" tvg-id="La7d.it" group-title="Italy",La7d
https://d15umi5iaezxgx.cloudfront.net/LA7D/CLN/HLS-B/Live.m3u8
#EXTINF:-1 tvg-name="Italia 2 Tv" tvg-logo="https://i.imgur.com/ISbxfY0.png" tvg-id="Italia2TV.it" group-title="Italy",Italia 2 Tv
https://59d7d6f47d7fc.streamlock.net/italia2/italia2/playlist.m3u8
#EXTINF:-1 tvg-name="Rete Tv Italia" tvg-logo="https://i.imgur.com/lXGWoV9.png" group-title="Italy",Rete Tv Italia
https://57068da1deb21.streamlock.net/retetvitalia/retetvitalia/playlist.m3u8
#EXTINF:-1 tvg-name="Rete 55" tvg-logo="https://i.imgur.com/EsZn2cj.png" group-title="Italy",Rete 55
https://live1.giocabet.tv/stream/6/index.m3u8
#EXTINF:-1,Canale 7 
http://wms.shared.streamshow.it/canale7/canale7/playlist.m3u8
#EXTINF:-1 tvg-name="Canale 10" tvg-logo="https://i.imgur.com/KuQcjYV.png" group-title="Italy",Canale 10
https://nrvideo1.newradio.it:1936/desxcerbht/desxcerbht/playlist.m3u8
#EXTINF:-1 tvg-name="Euro Tv" tvg-logo="https://i.imgur.com/HCl5Zbu.png" group-title="Italy",Euro Tv
https://5f22d76e220e1.streamlock.net/eurotv/eurotv/playlist.m3u8
#EXTINF:1 ,CafeTV24
https://srvx1.selftv.video/cafe/live/playlist.m3u8
#EXTINF:1 ,Alto Adige TV 
https://5f204aff97bee.streamlock.net/AltoAdigeTV/livestream/playlist.m3u8
#EXTINF:-1 tvg-name="Radio 105 TV Ⓖ" tvg-logo="https://i.imgur.com/3NiLKvj.png" tvg-id="Radio105TV.it" group-title="Italy",Radio 105 TV Ⓖ
https://live02-seg.msr.cdn.mediaset.net/live/ch-ec/ec-clr.isml/index.m3u8
#EXTINF:-1 tvg-name="Deejay TV" tvg-logo="https://i.imgur.com/rlaKH6k.png" tvg-id="DeejayTV.it" group-title="Italy",Deejay TV
https://4c4b867c89244861ac216426883d1ad0.msvdn.net/live/S85984808/sMO0tz9Sr2Rk/playlist.m3u8
#EXTINF:-1 tvg-name="RadioItaliaTV" tvg-logo="https://i.imgur.com/4VCEJuJ.png" tvg-id="RadioItaliaTV.it" group-title="Italy",RadioItaliaTV
https://radioitaliatv.akamaized.net/hls/live/2093117/RadioitaliaTV/master.m3u8
#EXTINF:-1 tvg-name="Radio KISS KISS TV" tvg-logo="https://i.imgur.com/UTStxDW.png" tvg-id="KissKissTV.it" group-title="Italy",Radio KISS KISS TV
https://kk.fluid.stream/KKMulti/smil:KissKissTV.smil/playlist.m3u8
#EXTINF:-1 tvg-name="R101 TV Ⓖ" tvg-logo="https://i.imgur.com/mWeEa9T.png" tvg-id="R101TV.it" group-title="Italy",R101 TV 
https://live02-seg.msr.cdn.mediaset.net/live/ch-er/er-clr.isml/index.m3u8
#EXTINF:-1 tvg-name="RTL 102.5" tvg-logo="https://i.imgur.com/KdissvS.png" tvg-id="RTL1025TV.it" group-title="Italy",RTL 102.5
https://dd782ed59e2a4e86aabf6fc508674b59.msvdn.net/live/S97044836/tbbP8T1ZRPBL/playlist_video.m3u8
#EXTINF:-1 tvg-name="Super!" tvg-logo="https://i.imgur.com/zDByOwo.png" tvg-id="Super.it" group-title="Italy",Super! 
https://vimnitaly.akamaized.net/hls/live/2094034/super/master.m3u8
#EXTINF:-1 tvg-name="Extra Tv" tvg-logo="https://i.imgur.com/KCBurST.png" group-title="Italy",Extra Tv
https://rst2.saiuzwebnetwork.it:8081/extratvlive/index.m3u8
#EXTINF: -1 tvg-id="Sportitalia.it"  tvg-logo="https://www.tvdream.net/img/sportitalia.png" tvg-logo-small="https://www.tvdream.net/img/sportitalia.png" , Sportitalia
https://di-kzbhv8pw.vo.lswcdn.net/sportitalia/sihd/playlist.m3u8
#EXTINF:-1 tvg-id="sportitalia24live" tvg-name="SportItalia24live" tvg-logo="http://odmsto.com/uploads/tv_image/sm/sportitalia-24-live.jpg" ,SportItalia24live
https://di-kzbhv8pw.vo.lswcdn.net/sportitalia/smil:silive24.smil/playlist.m3u8
#EXTINF:-1 tvg-id="rtv s.marino sport" tvg-name="RTV S.Marino Sport" tvg-logo="http://odmsto.com/uploads/tv_image/sm/rtv-smarino-sport.png" ,RTV S.Marino Sport
https://d2hrvno5bw6tg2.cloudfront.net/smrtv-ch02/_definst_/smil:ch-02.smil/chunklist_b1692000_slita.m3u8
#EXTINF: -1 tvg-id="GoTv.it" tvg-logo="https://www.tvdream.net/img/go-tv.png" tvg-logo-small="https://www.tvdream.net/img/go-tv.png" , GO-TV
https://6zklxkbbdw9b-hls-live.mariatvcdn.it/msmotor/2f759512164fc6fe4acbed6a5648993a.sdp/playlist.m3u8
#EXTINF:-1 tvg-name="SuperTennis" tvg-logo="https://i.imgur.com/GzsPlbX.png" tvg-id="SuperTennis.it" group-title="Italy",SuperTennis
https://live-embed.supertennix.hiway.media/restreamer/supertennix_client/gpu-a-c0-16/restreamer/rtmp/hls/h24_supertennix/manifest.m3u8#EXTINF:-1 tvg-name="Radio Montecarlo TV Ⓖ" tvg-logo="https://i.imgur.com/3TMMXmS.png" tvg-id="RadioMonteCarloTV.it" group-title="Italy",Radio Montecarlo TV 
https://live02-seg.msr.cdn.mediaset.net/live/ch-bb/bb-clr.isml/index.m3u8
#EXTINF:-1 tvg-name="Virgin Radio TV Ⓖ" tvg-logo="https://i.imgur.com/7Im3HI1.png" tvg-id="VirginRadioTV.it" group-title="Italy",Virgin Radio TV 
https://live02-seg.msr.cdn.mediaset.net/live/ch-ew/ew-clr.isml/index.m3u8
#EXTINF:-1 tvg-name="Alto Adige Tv" tvg-logo="https://i.imgur.com/S2sCFQi.png" tvg-id="AltoAdigeTV.it" group-title="Italy",Alto Adige Tv
https://5f204aff97bee.streamlock.net/AltoAdigeTV/livestream/playlist.m3u8
#EXTINF:-1 tvg-name="Antenna 2 Bergamo" tvg-logo="https://i.imgur.com/NfvHIAw.png" group-title="Italy",Antenna 2 Bergamo
https://58f12ffd2447a.streamlock.net/Antenna2/livestream/playlist.m3u8
#EXTINF:-1 tvg-name="Antenna 3 Veneto Nord Est" tvg-logo="https://i.imgur.com/NiVHLwp.png" tvg-id="AntennaTreNordest.it" group-title="Italy",Antenna 3 Veneto Nord Est
https://59d7d6f47d7fc.streamlock.net/antennatreveneto/antennatreveneto.stream/playlist.m3u8
#EXTINF:-1 tvg-name="Antenna Sud" tvg-logo="https://i.imgur.com/b8y6ImZ.png" group-title="Italy",Antenna Sud
https://live.antennasudwebtv.it:9443/hls/vod.m3u8
#EXTINF:-1 tvg-name="Antenna Sud Extra" tvg-logo="https://i.imgur.com/6tBv8VD.png" group-title="Italy",Antenna Sud Extra
https://live.antennasudwebtv.it:9443/hls/vod92.m3u8
#EXTINF:-1 tvg-name="Aristanis SuperTv" tvg-logo="https://i.imgur.com/v8PlAJO.png" group-title="Italy",Aristanis SuperTv
https://video2.azotosolutions.com:1936/supertvoristano/supertvoristano/playlist.m3u8
#EXTINF:-1 tvg-name="Arte Network Orler" tvg-logo="https://i.imgur.com/DP5y0Er.png" group-title="Italy",Arte Network Orler
https://tsw.streamingwebtv24.it:1936/artenetwork/artenetwork/playlist.m3u8
#EXTINF:-1 tvg-name="Aurora Arte" tvg-logo="https://i.imgur.com/BoLZ5wG.png" tvg-id="AuroraArte.it" group-title="Italy",Aurora Arte
https://59d7d6f47d7fc.streamlock.net/auroraarte/auroraarte/playlist.m3u8
#EXTINF:-1 tvg-name="Azzurra Tv Vco" tvg-logo="https://i.imgur.com/mSWw8uW.png" tvg-id="AzzurraTV.it" group-title="Italy",Azzurra Tv Vco
https://59d7d6f47d7fc.streamlock.net/azzurratv/azzurratv/playlist.m3u8
#EXTINF:1 ,Elive Brescia TV 
http://59d7d6f47d7fc.streamlock.net:1935/elivebresciatv/elivebresciatv/playlist.m3u8
#EXTINF: -1 tvg-id="InterTV.it" tvg-name="Inter TV" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Inter_TV_-_Logo_2017.svg/200px-Inter_TV_-_Logo_2017.svg.png" , Inter TV
https://open.http.mp.streamamg.com/p/3001560/sp/300156000/playManifest/entryId/0_xmkk2kjr/flavorIds/0_zlbr85f8,0_zlbr85f8,0_noewhew2/format/applehttp/protocol/https/a.m3u8

**Comment by ipstreet312** [comment]
thx will be added asap
