### ISSUE TITLE
Fama TV FM (Portugal) has changed its stream

### ISSUE THREAD

**Issue by thomraider12** [ipstreet312/freeiptv#43]
Fama TV no longer uses the link "https://streamer-a03.videos.sapo.pt/live/famatv/playlist.m3u8", and it changed to "https://204280.global.ssl.fastly.net/64cd4f589272294ee667108d/live_2f24d2e05bfd11eeb524673aae68b8ac/playlist.m3u8"

Here is proof:
![image](https://github.com/user-attachments/assets/cb483f39-3ad7-4e8e-b387-a1cb3c1e046c)
(link you currently have)

![image](https://github.com/user-attachments/assets/938a0fe1-f2f9-4f6a-8f09-342f90eba8b3)
(link i showed you)

Thank you.

**Comment by ipstreet312** [comment]
Thanks will be updated asap.

**Comment by thomraider12** [comment]
No problem.
