### ISSUE TITLE
Iran Channels

### ISSUE THREAD

**Issue by worldmediaman** [ipstreet312/freeiptv#44]
do you want add a Update 

please add this first 

#EXTINF:0 group-title="🇮🇷 IRAN"tvg-logo="https://m.media-amazon.com/images/I/31Zz4i8gviL.jpg" , MBC Persia 
https://shls-mbcpersia-prod-dub.shahid.net/out/v1/bdc7cd0d990e4c54808632a52c396946/index.m3u8

**Comment by ipstreet312** [comment]
Thanks. moved from mbc thematics into iran group section. regards

**Comment by ipstreet312** [comment]
Thanks again. added
