### ISSUE TITLE
Add Disney Channel Spain, Disney Channel Germany, Paramount Network Spain and TEN

### ISSUE THREAD

**Issue by joaquinito2070** [ipstreet312/freeiptv#46]
Add Disney Channel Spain, Disney Channel Germany, Paramount Network Spain and TEN

**Comment by ipstreet312** [comment]
No, only free channels. regards

**Comment by ipstreet312** [comment]
no pay channels, regards

**Comment by joaquinito2070** [comment]
Disney Channel Spain is free channel in Spain

**Comment by joaquinito2070** [comment]
Disney Channel Germany also is free.

**Comment by joaquinito2070** [comment]
Paramount Network Spain is also free.

**Comment by joaquinito2070** [comment]
And TEN is free also.

**Comment by ipstreet312** [comment]
Ok thanks for informations. I did not succeed to find them links, even on platforms like samsungplus pluto.
