### ISSUE TITLE
two portugal channels arent working

### ISSUE THREAD

**Issue by spotanjo3** [ipstreet312/freeiptv#5]
Hate to tell you but Maderia and Memoria arent working at all. Can you adding Biggs and Sic Internacional if its possible ?

**Comment by ipstreet312** [comment]
Rtp works. Others free channels will be added if founded

**Comment by spotanjo3** [comment]
What ? What did you do ? I try Memoria:

https://streaming-live.rtp.pt/liverepeater/smil:rtpmem.smil/playlist.m3u8 ----- not working. For VLC Player, The same for Madeira.

**Comment by ipstreet312** [comment]
You have to use specific user agent otherwise stream not opened on vlc regards

**Comment by spotanjo3** [comment]
How, may I ask ?

**Comment by ipstreet312** [comment]
Hello as example please use this structure into a m3u created file opened with vlc  : 

` #EXTINF:0,RTP Memoria
#EXTVLCOPT:http-user-agent=RTP Play/1.0.36
https://streaming-live.rtp.pt/liverepeater/smil:rtpmem.smil/playlist.m3u8
`

**Comment by campones** [comment]
j ai trouvé qq liens par hasard.
tvi reality (pt) https://video-auth5.iol.pt/live_tvi_reality/live_tvi_reality/edge_servers/tvireality-720_passthrough/chunks.m3u8
tvi ficçao (pt) https://video-auth2.iol.pt/live_tvi_ficcao/live_tvi_ficcao/edge_servers/tvificcao-720p/chunks.m3u8
sic (pt) https://d1zx6l1dn8vaj5.cloudfront.net/out/v1/b89cc37caa6d418eb423cf092a2ef970/index_4.m3u8 (je sais pas si ça durera)
