### ISSUE TITLE
groupe m6

### ISSUE THREAD

**Issue by campones** [ipstreet312/freeiptv#7]
hello

looks like we lost m6 w9 and 6ter

https://origin2-6play.live.6cloud.fr/pool_u81ytesz/m6/sixplayhde/hls_short_enc_m6/NA/vpnjbv4/index.m3u8

asking for some keys etc related to amazon

https://www.msp360.com/resources/blog/how-to-find-your-aws-access-key-id-and-secret-access-key/

**Comment by LeBazarDeBryan** [comment]
Try this :

M6 : http://livetv.ktv.zone/8/play.m3u8
W9 : http://livetv.ktv.zone/11/play.m3u8
6ter : http://livetv.ktv.zone/24/play.m3u8

**Comment by campones** [comment]
this doesn't work afaik

**Comment by LeBazarDeBryan** [comment]
> this doesn't work afaik (I have connection reset while hitting those link and not 2 days ago so..)
> 
> tell me how it works for you?

I use VLC

**Comment by mikhoul** [comment]
Work fine here (Canada) with VLC at least !

**Comment by campones** [comment]
it was working for me too 3 days ago and curiously, I get connection refused now

**Comment by campones** [comment]
btw, those links are great on vlc or smp but that's pretty much all about it, nothing else to do with them

**Comment by ipstreet312** [comment]
Hello and thanks to all, just a recent solution for Gulli from m6 group has found please find it here, dont able for m6 w9 i dont know. Here is https://raw.githubusercontent.com/ipstreet312/freeiptv/master/feed/gulliapr23.m3u8

**Comment by ipstreet312** [comment]
Hello all for m6 and gulli find here please : 
https://raw.githubusercontent.com/ipstreet312/freeiptv/master/feed/m6apr23.m3u8
https://raw.githubusercontent.com/ipstreet312/freeiptv/master/feed/gullihdapr23.m3u8
