### ISSUE TITLE
Belgique 

### ISSUE THREAD

**Issue by djermane** [ipstreet312/freeiptv#9]
can you try with rtl play [belge] links I guess similar to 6play fr
???

**Comment by ipstreet312** [comment]
you can put here links if channels are free to air to get, thanks!

**Comment by ipstreet312** [comment]
https://github.com/ipstreet312/freeiptv/tree/master/feed

**Comment by djermane** [comment]
can you try to add https://lespritsorcier.tv/direct.php
la chaine esprit SORCIER

**Comment by ipstreet312** [comment]
Thank you, but the required 'referrer' argument not managed on m3u ip tv players for that kind specifity of stream, regards

**Comment by mikhoul** [comment]
> Thank you, but the required 'referrer' argument not managed on m3u ip tv players for that kind specifity of stream, regards

Referers are supported on most Android IPTV players like Tivimate, PerfectPlayer and many others.

https://old.reddit.com/r/TiviMate/comments/gwem6k/does_tivimate_support_http_headers/

**Comment by ipstreet312** [comment]
Than you too much for your info. I will look for,  regards
